version: '3.9'

services:
  backend_service:
    build: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
#  frontend_service:
#    build: ./frontend
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./frontendt:/app
#    environment:
#      - REACT_APP_NAME=testing
#      - CHOKIDAR_USEPOLLING=true
#    depends_on:
#      - backend_service
  db:
    image: "postgres:15.0"
    ports:
      - "32700:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres