"""Second migration

Revision ID: 405b5a6cd24a
Revises: 9d7e00ea503c
Create Date: 2023-04-20 14:02:06.417402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405b5a6cd24a'
down_revision = '9d7e00ea503c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_history', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('login_history', 'created_at')
    # ### end Alembic commands ###
